server:
  port: 3344

spring:
  application:
    name: cloud-config-server #注册进eureka 的微服务名
  cloud:
    config:
      server:
        git:
          #ssh  私有  ssh-keygen -m pem -t rsa -C "xxx@xx.com"
          uri: git@github.com:kcTest/mscloud-config-center.git
          #https 公有
          #          uri: https://github.com/kcTest/mscloud-config-center.git # github上项目对应仓库的名称
          #          username: 763336180@qq.com
          #          password: 85014619woshiwww
          #          skip-ssl-validation: true
          # 搜索目录
          search-paths: /
      #读取分支
      label: master
#eureka注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka