server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: centos003:1111 #nacos注册及配置服务中心

    sentinel:
      transport:
        dashboard: mycentos:8858 #sentinel dashboard地址
        port: 8719  #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直到找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: centos003:1111
            #namespace: fcc8cd45-994f-4b19-a530-6f417425e8f4
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"  #监控使用