server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称 用于binding整合
          type: rabbit #消息中间件类型
          environment: #设置rabbitmq的相关环境配置
            spring:
              rabbitmq:
                host: centos003
                port: 5620
                username: admin
                password: 8585739wo
      bindings: #服务的整合处理
        autoReceiveB-in-0:
          destination: ExchangeB
          content-type: application/json
          binder: defaultRabbit
#         group: GPA 去掉分组 消息未持久化 重新启动后消息丢失

#        input: #这个名字是一个通道的名称
#          destination: ExchangeA #表示要使用的Exchange名称定义
#          content-type: application/json #设置消息类型 本次为json 文本设置“text/plain”
#          binder: defaultRabbit #设置要绑定的消息服务的具体设置

eureka:
  client: #客户端进行eureka注册的配置
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔（默认是90秒）
    instance-id: receive-8802.com #在信息列表时显示的主机名称
    prefer-ip-address: true #在信息列表时访问路径可以显示为ip
