server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能 利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route #路由的ID 没有固定规则但要求唯一 建议配合服务名
          # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言 路径相匹配的进行路由
        - id: payment_routh2 #payment_route #路由的ID 没有固定规则但要求唯一 建议配合服务名
          # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言 路径相匹配的进行路由
            - After=2021-10-29T14:27:01.466429700+08:00[Asia/Shanghai]
            #- Before=2021-10-29T15:27:01.466429700+08:00[Asia/Shanghai]
            #- Between=2021-10-29T15:27:01.466429700+08:00[Asia/Shanghai],2021-10-29T16:27:01.466429700+08:00[Asia/Shanghai]
            - Cookie=username,zkc  #通过cookie名称和值的正则表达式匹配
            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
            - Host=www.zkc.com #请求头的Host
            - Method=GET
            - Query=q,zkc
            - Query=q2,zkc2
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: #服务提供者provider注册进eureka
      defaultZone: http://eureka7001.com:7001/eureka
